export const usuarios = [
  {
    id: 1,
    nombre: "Pedro",
    apellido: "Lopez",
    numOrden: 8394,
    numeroCuadrilla: 2,
    totalPuntos: 300,
  },
  {
    id: 2,
    nombre: "María",
    apellido: "González",
    numOrden: 3894,
    numeroCuadrilla: 1,
    totalPuntos: 450,
  },
  {
    id: 3,
    nombre: "Juan",
    apellido: "Martínez",
    numOrden: 3094,
    numeroCuadrilla: 3,
    totalPuntos: 275,
  },
  {
    id: 4,
    nombre: "Ana",
    apellido: "Rodríguez",
    numOrden: 9394,
    numeroCuadrilla: 2,
    totalPuntos: 380,
  },
  {
    id: 5,
    nombre: "Carlos",
    apellido: "Sánchez",
    numOrden: 3094,
    numeroCuadrilla: 1,
    totalPuntos: 420,
  },
  {
    id: 6,
    nombre: "Laura",
    apellido: "Fernández",
    numOrden: 3914,
    numeroCuadrilla: 3,
    totalPuntos: 310,
  },
  {
    id: 7,
    nombre: "Miguel",
    apellido: "Pérez",
    numOrden: 1134,
    numeroCuadrilla: 2,
    totalPuntos: 290,
  },
  {
    id: 8,
    nombre: "Sofía",
    apellido: "Gómez",
    numOrden: 8293,
    numeroCuadrilla: 1,
    totalPuntos: 400,
  },
  {
    id: 9,
    nombre: "Javier",
    apellido: "Díaz",
    numOrden: 2994,
    numeroCuadrilla: 3,
    totalPuntos: 330,
  },
  {
    id: 10,
    nombre: "Elena",
    apellido: "Torres",
    numOrden: 1939,
    numeroCuadrilla: 2,
    totalPuntos: 360,
  },
];
